version: '3.7'
#
services:
  mongodb:
    container_name: test
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=test_pass
    volumes:
      - mongodb_container:/data/db    

volumes:
  mongodb_container:      